import React, { useEffect, useMemo, useRef, useState } from 'react';
import { motion } from 'framer-motion';
import {
  SandpackCodeEditor,
  SandpackLayout,
  SandpackPreview,
  SandpackProvider,
} from '@codesandbox/sandpack-react';
import DiffMatchPatch from 'diff-match-patch';
import JSZip from 'jszip';
import { GeneratedFile } from '../../types';

interface Props { files: GeneratedFile[]; previousFiles: GeneratedFile[]; activeFile: string | null; onSelectFile: (path: string) => void; streaming: boolean; }
type OutputTab = 'files' | 'preview';
type Viewport = 'desktop' | 'tablet' | 'mobile';
const TEST_PATH = /(?:^|\/)(?:__tests__\/|.*\.(?:test|spec)\.[jt]sx?$)/i;
const BACKEND_ROOT = /^(?:backend|server|api|functions)(?:\/|$)/i;
const COLORS: Record<string, string> = { ts: '#d60019', tsx: '#d60019', typescript: '#d60019', js: '#d60019', jsx: '#d60019', css: '#d60019', json: '#d60019', html: '#e8a46c', sql: '#d60019' };
const VIEWPORTS: Record<Viewport, { label: string; glyph: string; width: number }> = {
  desktop: { label: 'DESKTOP', glyph: '▰', width: 1440 }, tablet: { label: 'TABLET', glyph: '▯', width: 820 }, mobile: { label: 'MOBILE', glyph: '▯', width: 390 },
};
const SANDPACK_THEME = { colors: { surface1: '#0a0908', surface2: '#0a0908', surface3: '#171514111', clickable: '#7a756d', base: '#b7b2a9', disabled: '#3d3835333', hover: '#d60019', accent: '#d60019', error: '#d60019', errorSurface: '#120d0c' }, syntax: { plain: '#b7b2a9', comment: { color: '#5c5852555', fontStyle: 'italic' as const }, keyword: '#d60019', tag: '#d60019', punctuation: '#7a756d', definition: '#d60019', property: '#d60019', static: '#d60019', string: '#d60019' }, font: { body: 'JetBrains Mono, monospace', mono: 'JetBrains Mono, monospace', size: '12px', lineHeight: '1.6' } };
const visualizerButton: React.CSSProperties = { background: '#0a0908', border: '1px solid #2a2624', color: '#7a756d', padding: '4px 8px', fontFamily: '"JetBrains Mono", monospace', fontSize: 8, fontWeight: 700, letterSpacing: 1, cursor: 'pointer', whiteSpace: 'nowrap' };

async function downloadZip(files: GeneratedFile[]): Promise<void> { const zip = new JSZip(); files.forEach(file => zip.file(file.path, file.content)); const blob = await zip.generateAsync({ type: 'blob' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'fullkonk-output.zip'; anchor.click(); URL.revokeObjectURL(url); }
function makeHtml(files: GeneratedFile[]): string | null { const htmlFile = files.find(file => /\.html?$/i.test(file.path)); if (!htmlFile) return null; const css = files.filter(file => /\.css$/i.test(file.path)).map(file => `<style>\n${file.content}\n</style>`).join('\n'); const js = files.filter(file => /\.js$/i.test(file.path) && !TEST_PATH.test(file.path)).map(file => `<script type="module">\n${file.content}\n<\/script>`).join('\n'); const injected = `${css}\n${js}`; return /<\/body>/i.test(htmlFile.content) ? htmlFile.content.replace(/<\/body>/i, `${injected}\n</body>`) : `${htmlFile.content}\n${injected}`; }

function HtmlPreview({ files, reloadKey }: { files: GeneratedFile[]; reloadKey: number }) {
  const html = useMemo(() => makeHtml(files), [files]); const [url, setUrl] = useState('');
  useEffect(() => { if (!html) { setUrl(''); return; } const nextUrl = URL.createObjectURL(new Blob([html], { type: 'text/html' })); setUrl(nextUrl); return () => URL.revokeObjectURL(nextUrl); }, [html, reloadKey]);
  if (!url) return <EmptyPreview text="NO HTML ENTRY FILE FOUND" />;
  return <iframe title="Interactive generated product" sandbox="allow-scripts allow-forms allow-modals allow-popups" src={url} style={{ width: '100%', height: '100%', border: 0, background: '#f4f1eb', display: 'block' }} />;
}
function EmptyPreview({ text }: { text: string }) { return <div style={{ height: '100%', display: 'grid', placeItems: 'center', color: '#5c5852', fontFamily: '"JetBrains Mono", monospace', fontSize: 10, letterSpacing: 2 }}>{text}</div>; }

export function normalizeSandpackFiles(files: GeneratedFile[]): Record<string, string> {
  const previewable = files.filter(file => {
    const normalizedPath = file.path.replace(/\\/g, '/').replace(/^\.\//, '').replace(/^\/+/, '');
    return /\.(tsx?|jsx?|css|json|html)$/i.test(normalizedPath) && !TEST_PATH.test(normalizedPath) && !BACKEND_ROOT.test(normalizedPath);
  });
  const normalizedPaths = previewable.map(file => file.path.replace(/\\/g, '/').replace(/^\.\//, '').replace(/^\/+/, ''));
  const appIndex = normalizedPaths.findIndex(path => /(?:^|\/)src\/App\.[jt]sx?$/i.test(path));
  const mainIndex = normalizedPaths.findIndex(path => /(?:^|\/)src\/(?:main|index)\.[jt]sx?$/i.test(path));
  const looseAppIndex = normalizedPaths.findIndex(path => /(?:^|\/)App\.[jt]sx?$/i.test(path));
  const anchorIndex = appIndex >= 0 ? appIndex : mainIndex >= 0 ? mainIndex : looseAppIndex;
  const anchorPath = anchorIndex >= 0 ? normalizedPaths[anchorIndex] : '';
  const srcPosition = anchorPath.toLowerCase().lastIndexOf('/src/');
  const projectRoot = /^src\//i.test(anchorPath) ? '' : srcPosition >= 0 ? anchorPath.slice(0, srcPosition + 1) : anchorPath.includes('/') ? anchorPath.slice(0, anchorPath.lastIndexOf('/') + 1) : '';
  const result: Record<string, string> = {};
  previewable.forEach((file, index) => { const sourcePath = normalizedPaths[index]; if (projectRoot && !sourcePath.startsWith(projectRoot)) return; const relativePath = projectRoot ? sourcePath.slice(projectRoot.length) : sourcePath; result[`/${relativePath}`] = file.content; });
  const mappedPaths = Object.keys(result); const mappedApp = mappedPaths.find(path => /(?:^|\/)App\.[jt]sx?$/i.test(path)); const mappedMain = mappedPaths.find(path => /\/src\/(?:main|index)\.[jt]sx?$/i.test(path));
  if (!result['/src/index.tsx']) { if (mappedMain && !/\/index\.[jt]sx?$/i.test(mappedMain)) { const target = mappedMain.replace(/^\/src\//, './').replace(/\.[jt]sx?$/i, ''); result['/src/index.tsx'] = `import '${target}';`; } else if (mappedApp) { const target = mappedApp.startsWith('/src/') ? mappedApp.replace(/^\/src\//, './').replace(/\.[jt]sx?$/i, '') : `..${mappedApp.replace(/\.[jt]sx?$/i, '')}`; result['/src/index.tsx'] = ["import React from 'react';", "import { createRoot } from 'react-dom/client';", `import App from '${target}';`, "createRoot(document.getElementById('root')!).render(", '  <React.StrictMode>', '    <App />', '  </React.StrictMode>,', ');'].join('\n'); } }
  const fallbackDependencies: Record<string, string> = { react: '^18.2.0', 'react-dom': '^18.2.0', 'react-scripts': '^5.0.1', 'react-router-dom': '^6.28.0', motion: '^12.0.0', 'framer-motion': '^12.0.0', 'lucide-react': '^0.468.0', recharts: '^2.15.0', zod: '^3.24.0', clsx: '^2.1.1', 'tailwind-merge': '^2.6.0', 'date-fns': '^4.1.0' };
  let generatedPackage: { dependencies?: Record<string, string>; devDependencies?: Record<string, string> } = {};
  if (result['/package.json']) { try { generatedPackage = JSON.parse(result['/package.json']) as typeof generatedPackage; } catch { generatedPackage = {}; } }
  result['/package.json'] = JSON.stringify({ scripts: { start: 'react-scripts start' }, dependencies: { ...fallbackDependencies, ...(generatedPackage.dependencies || {}), ...(generatedPackage.devDependencies || {}), 'react-scripts': '^5.0.1' } }, null, 2);
  result['/public/index.html'] ||= ['<!doctype html>', '<html>', '<head>', '<meta charset="UTF-8">', '<meta', '  name="viewport"', '  content="width=device-width,initial-scale=1"', '>', '<script src="https://cdn.tailwindcss.com"></script>', '</head>', '<body>', '<div id="root"></div>', '</body>', '</html>'].join('');
  return result;
}

interface VisualizerProps { files: GeneratedFile[]; sandpackFiles: Record<string, string>; isReact: boolean; hasHtml: boolean; }
function InteractiveVisualizer({ files, sandpackFiles, isReact, hasHtml }: VisualizerProps) {
  const [viewport, setViewport] = useState<Viewport>('desktop'); const [showEditor, setShowEditor] = useState(false); const [fullscreen, setFullscreen] = useState(false); const [reloadKey, setReloadKey] = useState(0); const canPreview = isReact || hasHtml; const viewportConfig = VIEWPORTS[viewport];
  const activeSandpackFile = Object.keys(sandpackFiles).find(path => /\/src\/App\.[jt]sx?$/i.test(path)) || Object.keys(sandpackFiles).find(path => /(?:^|\/)App\.[jt]sx?$/i.test(path)) || Object.keys(sandpackFiles).find(path => /\/src\/(?:main|index)\.[jt]sx?$/i.test(path)) || '/src/index.tsx';
  useEffect(() => { if (!fullscreen) return; const onKeyDown = (event: KeyboardEvent) => { if (event.key === 'Escape') setFullscreen(false); }; window.addEventListener('keydown', onKeyDown); return () => window.removeEventListener('keydown', onKeyDown); }, [fullscreen]);
  const visualizer = <div style={{ display: 'flex', flexDirection: 'column', height: '100%', minHeight: 0, background: '#0a0908' }}>
    <div style={{ display: 'flex', alignItems: 'center', gap: 8, minHeight: 38, padding: '0 10px', background: '#0a0908', borderBottom: '1px solid #2a2624', flexShrink: 0, overflowX: 'auto', fontFamily: '"JetBrains Mono", monospace' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 6, color: '#d60019', fontSize: 8, fontWeight: 700, letterSpacing: 1, whiteSpace: 'nowrap' }}><motion.span animate={{ opacity: [1, .3, 1] }} transition={{ duration: 1.2, repeat: Infinity }} style={{ width: 6, height: 6, background: '#d60019', boxShadow: '0 0 7px #d60019' }} />LIVE PRODUCT</div>
      <div style={{ display: 'flex', marginLeft: 6 }}>{(Object.keys(VIEWPORTS) as Viewport[]).map(value => <button key={value} onClick={() => { setViewport(value); if (value !== 'desktop') setShowEditor(false); }} style={{ ...visualizerButton, color: viewport === value ? '#0a0908' : '#7a756d', background: viewport === value ? '#d60019' : '#0a0908', borderColor: viewport === value ? '#d60019' : '#2a2624' }}>{VIEWPORTS[value].glyph} {VIEWPORTS[value].label}</button>)}</div>
      <span style={{ color: '#3d3835', fontSize: 8, letterSpacing: 1, whiteSpace: 'nowrap' }}>{viewportConfig.width}px</span><div style={{ flex: 1 }} />
      {isReact && <button onClick={() => setShowEditor(value => !value)} style={{ ...visualizerButton, color: showEditor ? '#d60019' : '#7a756d' }}>{showEditor ? 'HIDE EDITOR' : 'EDIT UI'}</button>}
      <button onClick={() => setReloadKey(value => value + 1)} style={visualizerButton}>↻ RESTART</button><button onClick={() => setFullscreen(value => !value)} style={{ ...visualizerButton, color: fullscreen ? '#d60019' : '#b7b2a9' }}>{fullscreen ? '✕ EXIT' : '⛶ FOCUS'}</button>
    </div>
    <div style={{ display: 'flex', alignItems: 'center', gap: 7, padding: '7px 10px', background: '#0a0908', borderBottom: '1px solid #171514', flexShrink: 0, fontFamily: '"JetBrains Mono", monospace' }}><span style={{ width: 5, height: 5, background: canPreview ? '#d60019' : '#d60019' }} /><div style={{ flex: 1, maxWidth: 560, padding: '5px 10px', border: '1px solid #2a2624', background: '#0a0908', color: '#5c5852', fontSize: 9, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>fullkonk://generated-product/</div><span style={{ color: '#3d3835', fontSize: 8, letterSpacing: 1 }}>INTERACT MODE</span></div>
    <div style={{ flex: 1, minHeight: 0, overflow: 'auto', padding: viewport === 'desktop' ? 0 : '24px 16px', background: '#0a0908' }}><div style={{ width: viewport === 'desktop' ? '100%' : `min(100%, ${viewportConfig.width}px)`, height: viewport === 'desktop' ? '100%' : 'max(680px, calc(100% - 8px))', margin: '0 auto', border: viewport === 'desktop' ? 0 : '2px solid #3d3835', background: '#f4f1eb', boxShadow: viewport === 'desktop' ? 'none' : '10px 10px 0 #171514', overflow: 'hidden' }}>
      {!canPreview ? <EmptyPreview text="VISUALIZER REQUIRES A REACT OR HTML ENTRY FILE" /> : isReact ? <SandpackProvider key={reloadKey} template="react-ts" files={sandpackFiles} theme={SANDPACK_THEME} options={{ activeFile: activeSandpackFile, visibleFiles: [activeSandpackFile] }}><SandpackLayout style={{ height: '100%', border: 0, borderRadius: 0, display: 'flex' }}>{showEditor && <SandpackCodeEditor showTabs showLineNumbers showInlineErrors wrapContent style={{ height: '100%', minWidth: 320, flex: '0 0 44%', borderRadius: 0 }} />}<SandpackPreview showNavigator={false} showRefreshButton={false} showOpenInCodeSandbox={false} showOpenNewtab={false} showSandpackErrorOverlay style={{ height: '100%', flex: 1, borderRadius: 0 }} /></SandpackLayout></SandpackProvider> : <HtmlPreview key={reloadKey} files={files} reloadKey={reloadKey} />}
    </div></div>
    <div style={{ display: 'flex', justifyContent: 'space-between', padding: '5px 10px', borderTop: '1px solid #171514', background: '#0a0908', color: '#3d3835', fontFamily: '"JetBrains Mono", monospace', fontSize: 8, letterSpacing: 1, flexShrink: 0 }}><span>CLICK · TYPE · NAVIGATE · TEST</span><span>{isReact ? 'REACT RUNTIME' : 'HTML SANDBOX'} · ISOLATED</span></div>
  </div>;
  if (!fullscreen) return visualizer; return <div role="dialog" aria-modal="true" aria-label="Interactive product visualizer" style={{ position: 'fixed', inset: 0, zIndex: 10000, background: '#0a0908', padding: 10 }}>{visualizer}</div>;
}

export default function CodeOutput({ files, previousFiles, activeFile, onSelectFile, streaming }: Props) {
  const [tab, setTab] = useState<OutputTab>('files'); const [copied, setCopied] = useState(false); const [showDiff, setShowDiff] = useState(false); const wasStreaming = useRef(streaming); const current = files.find(file => file.path === activeFile) || files[0] || null; const previous = current ? previousFiles.find(file => file.path === current.path) : undefined; const html = useMemo(() => makeHtml(files), [files]); const sandpackFiles = useMemo(() => normalizeSandpackFiles(files), [files]); const isReact = Object.keys(sandpackFiles).some(path => /(?:^|\/)(?:src\/(?:App|main|index)|App)\.[jt]sx?$/i.test(path));
  useEffect(() => setShowDiff(false), [current?.path]); useEffect(() => { if (!copied) return; const timer = window.setTimeout(() => setCopied(false), 1400); return () => window.clearTimeout(timer); }, [copied]); useEffect(() => { if (wasStreaming.current && !streaming && (isReact || Boolean(html))) setTab('preview'); wasStreaming.current = streaming; }, [html, isReact, streaming]);
  const diffLines = useMemo(() => { if (!current || !previous) return []; const dmp = new DiffMatchPatch(); return dmp.diff_main(previous.content, current.content).flatMap(([operation, text], group) => text.split('\n').map((line, index) => ({ key: `${group}-${index}`, operation, line }))); }, [current, previous]);
  if (files.length === 0) return <EmptyPreview text={streaming ? 'GENERATING PRODUCT...' : 'OUTPUT APPEARS HERE'} />;
  return <section style={{ display: 'flex', flexDirection: 'column', height: '100%', background: '#0a0908', minWidth: 0 }}><div style={{ display: 'flex', background: '#0a0908', borderBottom: '1px solid #2a2624', flexShrink: 0 }}>{(['files', 'preview'] as OutputTab[]).map(value => <button key={value} onClick={() => setTab(value)} style={{ padding: '9px 18px', border: 0, borderBottom: tab === value ? '2px solid #d60019' : '2px solid transparent', background: tab === value ? '#0a0908' : 'transparent', color: tab === value ? '#d60019' : '#5c5852', fontFamily: '"JetBrains Mono", monospace', fontSize: 9, fontWeight: 700, letterSpacing: 2, cursor: 'pointer' }}>{value === 'files' ? 'CODE' : 'VISUALIZER'}</button>)}{tab === 'preview' && <span style={{ alignSelf: 'center', color: '#d60019', fontFamily: '"JetBrains Mono", monospace', fontSize: 8, letterSpacing: 1, marginLeft: 12 }}>● INTERACTIVE</span>}<span style={{ marginLeft: 'auto', alignSelf: 'center', paddingRight: 14, color: '#3d3835', fontFamily: '"JetBrains Mono", monospace', fontSize: 8 }}>{files.length} FILES</span></div>
    {tab === 'preview' ? <div style={{ flex: 1, minHeight: 0, overflow: 'hidden' }}><InteractiveVisualizer files={files} sandpackFiles={sandpackFiles} isReact={isReact} hasHtml={Boolean(html)} /></div> : <><div style={{ display: 'flex', overflowX: 'auto', background: '#0a0908', borderBottom: '1px solid #171514', flexShrink: 0 }}>{files.map(file => { const active = file.path === current?.path; const color = COLORS[file.language.toLowerCase()] || '#5c5852'; return <button key={file.path} onClick={() => onSelectFile(file.path)} title={file.path} style={{ flexShrink: 0, padding: '7px 14px', border: 0, borderRight: '1px solid #171514', borderBottom: active ? `2px solid ${color}` : '2px solid transparent', background: active ? '#0a0908' : 'transparent', color: active ? '#f4f1eb' : '#5c5852', fontFamily: '"JetBrains Mono", monospace', fontSize: 10, cursor: 'pointer', whiteSpace: 'nowrap' }}>{(file.isTest || TEST_PATH.test(file.path)) ? '🧪 ' : ''}{file.path.split('/').pop()}</button>; })}</div>{current && <div style={{ display: 'flex', gap: 8, alignItems: 'center', padding: '6px 12px', borderBottom: '1px solid #171514', fontFamily: '"JetBrains Mono", monospace' }}><span style={{ flex: 1, minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis', color: '#5c5852', fontSize: 9 }}>{current.path}</span>{previous && <button onClick={() => setShowDiff(value => !value)} style={actionStyle}>{showDiff ? 'CODE' : 'DIFF'}</button>}<button onClick={() => { navigator.clipboard.writeText(current.content).catch(() => undefined); setCopied(true); }} style={actionStyle}>{copied ? '✓ COPIED' : 'COPY'}</button><button onClick={() => { void downloadZip(files); }} style={actionStyle}>ZIP</button></div>}<div style={{ flex: 1, overflow: 'auto' }}>{current && showDiff && previous ? <pre style={preStyle}>{diffLines.map(item => <div key={item.key} style={{ background: item.operation === 1 ? '#120d0c' : item.operation === -1 ? '#120d0c' : 'transparent', color: item.operation === 1 ? '#d60019' : item.operation === -1 ? '#ff1a2e' : '#7a756d' }}>{item.operation === 1 ? '+ ' : item.operation === -1 ? '- ' : '  '}{item.line || ' '}</div>)}</pre> : current && <div style={{ display: 'flex', minWidth: 'max-content' }}><div style={{ padding: '14px 10px', borderRight: '1px solid #171514', color: '#2a2624', fontFamily: '"JetBrains Mono", monospace', fontSize: 11, lineHeight: 1.7, textAlign: 'right', userSelect: 'none' }}>{current.content.split('\n').map((_, index) => <div key={index}>{index + 1}</div>)}</div><pre style={preStyle}>{current.content}</pre></div>}</div></>}</section>;
}
const actionStyle: React.CSSProperties = { background: '#0a0908', border: '1px solid #2a2624', color: '#7a756d', padding: '3px 9px', fontFamily: '"JetBrains Mono", monospace', fontSize: 8, cursor: 'pointer' };
const preStyle: React.CSSProperties = { margin: 0, padding: '14px 18px', color: '#b7b2a9', fontFamily: '"JetBrains Mono", monospace', fontSize: 11, lineHeight: 1.7, whiteSpace: 'pre', minWidth: 'max-content' };
