// components/fullkonk/GitHubExportModal.tsx

import { useState } from 'react';
import { motion } from 'framer-motion';
import { getAuth } from 'firebase/auth';
import { GeneratedFile } from '../../types';
import { GitHubExportResult } from '../../services/fullkonk.github';

interface Props {
  files:   GeneratedFile[];
  onClose: () => void;
}

export default function GitHubExportModal({ files, onClose }: Props) {
  const [token,   setToken]   = useState('');
  const [owner,   setOwner]   = useState('');
  const [repo,    setRepo]    = useState('');
  const [branch,  setBranch]  = useState('fullkonk-output');
  const [message, setMessage] = useState('Generated by fullKONK_> · konkred.xyz');
  const [loading, setLoading] = useState(false);
  const [result,  setResult]  = useState<GitHubExportResult | null>(null);
  const [error,   setError]   = useState('');

  const closeSecurely = () => {
    setToken('');
    onClose();
  };

  const handleExport = async () => {
    if (!token.trim() || !owner.trim() || !repo.trim()) {
      setError('Token, owner, and repo are required.');
      return;
    }
    setLoading(true);
    setError('');
    setResult(null);

    try {
      // Same-origin Vercel route: it injects the gateway x-brain-key server-side
      // and (when configured) uses a server-owned GitHub token, so the PAT below
      // never leaves konkred.xyz. The session token is attached so the route can
      // bind/verify the export when FULLKONK_REQUIRE_AUTH is enabled.
      const user = getAuth().currentUser;
      const idToken = user ? await user.getIdToken().catch(() => '') : '';
      const res = await fetch('/api/fullkonk/github/export', {
        method:  'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(idToken ? { Authorization: `Bearer ${idToken}` } : {}),
        },
        body: JSON.stringify({ files, token, owner, repo, branch, message }),
      });
      const data = await res.json().catch(() => ({})) as { error?: string; errors?: string[]; retryAfter?: number };
      if (!res.ok) {
        const retryHeader = Number(res.headers.get('retry-after'));
        const retryAfter = Number.isFinite(retryHeader) && retryHeader > 0 ? retryHeader : Number(data.retryAfter);
        const wait = Number.isFinite(retryAfter) && retryAfter > 0 ? ` Retry in ${Math.ceil(retryAfter)}s.` : '';
        throw new Error(`${data.error ?? data.errors?.[0] ?? 'Export failed'}${wait}`);
      }
      setResult(data as GitHubExportResult);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Export failed');
    } finally {
      setLoading(false);
    }
  };

  const inputStyle: React.CSSProperties = {
    width:      '100%',
    background: '#050505',
    border:     '1px solid #222',
    color:      '#fff',
    fontFamily: '"JetBrains Mono", monospace',
    fontSize:    11,
    padding:    '8px 10px',
    outline:    'none',
    boxSizing:  'border-box',
  };

  const labelStyle: React.CSSProperties = {
    fontFamily:    '"JetBrains Mono", monospace',
    fontSize:       9,
    color:          '#444',
    letterSpacing:  2,
    textTransform: 'uppercase',
    marginBottom:   5,
    display:       'block',
  };

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      style={{
        position:       'fixed',
        inset:           0,
        background:     'rgba(0,0,0,.9)',
        zIndex:          200,
        display:        'flex',
        alignItems:     'center',
        justifyContent: 'center',
        padding:         20,
      }}
      onClick={e => { if (e.target === e.currentTarget) closeSecurely(); }}
    >
      <motion.div
        initial={{ scale: .95, y: 16 }}
        animate={{ scale: 1, y: 0 }}
        style={{
          background:  '#0a0a0a',
          border:      '3px solid #1a1a1a',
          width:       '100%',
          maxWidth:     480,
          fontFamily: '"JetBrains Mono", monospace',
        }}
      >
        {/* Header */}
        <div style={{
          display:        'flex',
          alignItems:     'center',
          justifyContent: 'space-between',
          padding:         '12px 16px',
          borderBottom:   '1px solid #1a1a1a',
        }}>
          <span style={{ fontSize: 10, letterSpacing: 3, color: '#FFD700', textTransform: 'uppercase' }}>
            // EXPORT TO GITHUB
          </span>
          <button onClick={closeSecurely} style={{ background: 'none', border: '1px solid #222', color: '#555', width: 26, height: 26, cursor: 'pointer', fontSize: 12 }}>
            ✕
          </button>
        </div>

        <div style={{ padding: '20px 16px', display: 'flex', flexDirection: 'column', gap: 14 }}>
          {/* File count */}
          <div style={{ fontSize: 10, color: '#444', padding: '8px 10px', border: '1px solid #111', background: '#050505' }}>
            {files.length} file{files.length !== 1 ? 's' : ''} ready to export
            <div style={{ marginTop: 6, display: 'flex', flexWrap: 'wrap', gap: 4 }}>
              {files.slice(0, 6).map(f => (
                <span key={f.path} style={{ fontSize: 8, color: '#333', padding: '2px 6px', border: '1px solid #111' }}>
                  {f.path.split('/').pop()}
                </span>
              ))}
              {files.length > 6 && (
                <span style={{ fontSize: 8, color: '#2a2a2a', padding: '2px 6px' }}>
                  +{files.length - 6} more
                </span>
              )}
            </div>
          </div>

          {/* GitHub Personal Access Token */}
          <div>
            <label style={labelStyle}>GitHub Token (repo scope)</label>
            <input
              type="password"
              value={token}
              onChange={e => setToken(e.target.value)}
              placeholder="ghp_..."
              style={inputStyle}
            />
            <div style={{ fontSize: 8, color: '#2a2a2a', marginTop: 4 }}>
              Token is sent to your server — never stored on konkred.xyz
            </div>
          </div>

          {/* Owner + Repo */}
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 }}>
            <div>
              <label style={labelStyle}>Owner / Org</label>
              <input value={owner} onChange={e => setOwner(e.target.value)} placeholder="yourusername" style={inputStyle} />
            </div>
            <div>
              <label style={labelStyle}>Repository</label>
              <input value={repo} onChange={e => setRepo(e.target.value)} placeholder="my-project" style={inputStyle} />
            </div>
          </div>

          {/* Branch */}
          <div>
            <label style={labelStyle}>Branch</label>
            <input value={branch} onChange={e => setBranch(e.target.value)} style={inputStyle} />
          </div>

          {/* Commit message */}
          <div>
            <label style={labelStyle}>Commit Message</label>
            <input value={message} onChange={e => setMessage(e.target.value)} style={inputStyle} />
          </div>

          {/* Error */}
          {error && (
            <div style={{ fontSize: 10, color: '#FF003C', padding: '8px 10px', border: '1px solid #FF003C', background: '#0d0000' }}>
              {error}
            </div>
          )}

          {/* Result */}
          {result && (
            <div style={{ fontSize: 10, padding: '10px', border: `1px solid ${result.success ? '#00FF88' : '#FF003C'}`, background: result.success ? '#001a00' : '#0d0000' }}>
              <div style={{ color: result.success ? '#00FF88' : '#FF003C', fontWeight: 700, marginBottom: 6 }}>
                {result.success ? `✓ ${result.filesUploaded} files exported` : '✕ Export failed'}
              </div>
              {result.prUrl && (
                <a href={result.prUrl} target="_blank" rel="noreferrer" style={{ color: '#FFD700', fontSize: 9, display: 'block', marginTop: 4 }}>
                  → View Pull Request
                </a>
              )}
              {result.errors.length > 0 && (
                <div style={{ marginTop: 6, color: '#FF003C', fontSize: 9 }}>
                  {result.errors.map((e, i) => <div key={i}>{e}</div>)}
                </div>
              )}
            </div>
          )}

          {/* Action */}
          {!result && (
            <button
              onClick={handleExport}
              disabled={loading}
              style={{
                background:    loading ? '#222' : '#FFD700',
                border:        'none',
                color:         loading ? '#555' : '#000',
                fontFamily:    '"JetBrains Mono", monospace',
                fontSize:       10,
                fontWeight:     700,
                letterSpacing:  2,
                padding:        '11px',
                cursor:         loading ? 'not-allowed' : 'pointer',
                transition:     'all .15s',
                textTransform: 'uppercase',
              }}
            >
              {loading ? 'EXPORTING...' : '↑ PUSH TO GITHUB'}
            </button>
          )}
        </div>
      </motion.div>
    </motion.div>
  );
}
