// components/fullkonk/GitHubExportModal.tsx

import { useState } from 'react';
import { motion } from 'framer-motion';
import { GeneratedFile } from '../../types';
import { GitHubExportResult, normalizeGitHubExportResult } from '../../services/fullkonk.github';

interface Props {
  files:   GeneratedFile[];
  onClose: () => void;
}

export default function GitHubExportModal({ files, onClose }: Props) {
  // No token state: the Konkred Gateway owns the GitHub credential server-side.
  // The browser never collects, stores or transmits a GitHub Personal Access
  // Token; the Vercel proxy strips any token field before forwarding.
  const [owner,   setOwner]   = useState('');
  const [repo,    setRepo]    = useState('');
  const [branch,  setBranch]  = useState('fullkonk-output');
  const [message, setMessage] = useState('Generated by fullKONK_> · konkred.xyz');
  const [loading, setLoading] = useState(false);
  const [result,  setResult]  = useState<GitHubExportResult | null>(null);
  const [error,   setError]   = useState('');

  const closeSecurely = () => {
    onClose();
  };

  const handleExport = async () => {
    if (loading) return; // prevent duplicate submissions
    if (!owner.trim() || !repo.trim()) {
      setError('Owner and repository are required.');
      return;
    }
    setLoading(true);
    setError('');
    setResult(null);

    try {
      const res = await fetch('/api/fullkonk/github/export', {
        method:  'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ files, owner: owner.trim(), repo: repo.trim(), branch: branch.trim(), message }),
      });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) {
        const detail = typeof data?.error === 'string' ? data.error
          : data?.error && typeof data.error === 'object' ? (data.error.message ?? 'Export failed')
          : `Export failed (${res.status}).`;
        throw new Error(detail);
      }
      setResult(normalizeGitHubExportResult(data));
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Export failed');
    } finally {
      setLoading(false);
    }
  };

  const inputStyle: React.CSSProperties = {
    width:      '100%',
    background: '#0a0908',
    border:     '1px solid #2a2624',
    color:      '#f4f1eb',
    fontFamily: '"JetBrains Mono", monospace',
    fontSize:    11,
    padding:    '8px 10px',
    outline:    'none',
    boxSizing:  'border-box',
  };

  const labelStyle: React.CSSProperties = {
    fontFamily:    '"JetBrains Mono", monospace',
    fontSize:       9,
    color:          '#5c5852',
    letterSpacing:  2,
    textTransform: 'uppercase',
    marginBottom:   5,
    display:       'block',
  };

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      style={{
        position:       'fixed',
        inset:           0,
        background:     'rgba(0,0,0,.9)',
        zIndex:          200,
        display:        'flex',
        alignItems:     'center',
        justifyContent: 'center',
        padding:         20,
      }}
      onClick={e => { if (e.target === e.currentTarget) closeSecurely(); }}
    >
      <motion.div
        initial={{ scale: .95, y: 16 }}
        animate={{ scale: 1, y: 0 }}
        style={{
          background:  '#0a0908',
          border:      '3px solid #2a2624',
          width:       '100%',
          maxWidth:     480,
          fontFamily: '"JetBrains Mono", monospace',
        }}
      >
        {/* Header */}
        <div style={{
          display:        'flex',
          alignItems:     'center',
          justifyContent: 'space-between',
          padding:         '12px 16px',
          borderBottom:   '1px solid #2a2624',
        }}>
          <span style={{ fontSize: 10, letterSpacing: 3, color: '#d60019', textTransform: 'uppercase' }}>
            // EXPORT TO GITHUB
          </span>
          <button onClick={closeSecurely} style={{ background: 'none', border: '1px solid #2a2624', color: '#5c5852', width: 26, height: 26, cursor: 'pointer', fontSize: 12 }}>
            ✕
          </button>
        </div>

        <div style={{ padding: '20px 16px', display: 'flex', flexDirection: 'column', gap: 14 }}>
          {/* File count */}
          <div style={{ fontSize: 10, color: '#5c5852', padding: '8px 10px', border: '1px solid #171514', background: '#0a0908' }}>
            {files.length} file{files.length !== 1 ? 's' : ''} ready to export
            <div style={{ marginTop: 6, display: 'flex', flexWrap: 'wrap', gap: 4 }}>
              {files.slice(0, 6).map(f => (
                <span key={f.path} style={{ fontSize: 8, color: '#3d3835', padding: '2px 6px', border: '1px solid #171514' }}>
                  {f.path.split('/').pop()}
                </span>
              ))}
              {files.length > 6 && (
                <span style={{ fontSize: 8, color: '#2a2624', padding: '2px 6px' }}>
                  +{files.length - 6} more
                </span>
              )}
            </div>
          </div>

          {/* Credential notice: the gateway owns the GitHub token */}
          <div style={{ fontSize: 9, color: '#d60019', padding: '8px 10px', border: '1px solid #3a201f', background: '#100e0d', lineHeight: 1.5 }}>
            // SECURE EXPORT — no token required in your browser.
            <br />
            The Konkred Gateway holds the server-managed GitHub credential and opens the pull request on your behalf.
          </div>

          {/* Owner + Repo */}
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 }}>
            <div>
              <label style={labelStyle}>Owner / Org</label>
              <input value={owner} onChange={e => setOwner(e.target.value)} placeholder="yourusername" style={inputStyle} />
            </div>
            <div>
              <label style={labelStyle}>Repository</label>
              <input value={repo} onChange={e => setRepo(e.target.value)} placeholder="my-project" style={inputStyle} />
            </div>
          </div>

          {/* Branch */}
          <div>
            <label style={labelStyle}>Branch</label>
            <input value={branch} onChange={e => setBranch(e.target.value)} style={inputStyle} />
          </div>

          {/* Commit message */}
          <div>
            <label style={labelStyle}>Commit Message</label>
            <input value={message} onChange={e => setMessage(e.target.value)} style={inputStyle} />
          </div>

          {/* Error */}
          {error && (
            <div style={{ fontSize: 10, color: '#d60019', padding: '8px 10px', border: '1px solid #d60019', background: '#120d0c' }}>
              {error}
            </div>
          )}

          {/* Result */}
          {result && (
            <div style={{ fontSize: 10, padding: '10px', border: `1px solid ${result.success ? '#d60019' : '#d60019'}`, background: result.success ? '#120d0c' : '#120d0c' }}>
              <div style={{ color: result.success ? '#d60019' : '#d60019', fontWeight: 700, marginBottom: 6 }}>
                {result.success ? `✓ ${result.filesUploaded} files exported` : '✕ Export failed'}
              </div>
              {result.prUrl && (
                <a href={result.prUrl} target="_blank" rel="noreferrer" style={{ color: '#d60019', fontSize: 9, display: 'block', marginTop: 4 }}>
                  → View Pull Request
                </a>
              )}
              {result.errors.length > 0 && (
                <div style={{ marginTop: 6, color: '#d60019', fontSize: 9 }}>
                  {result.errors.map((e, i) => <div key={i}>{e}</div>)}
                </div>
              )}
            </div>
          )}

          {/* Action */}
          {!result && (
            <button
              onClick={handleExport}
              disabled={loading}
              style={{
                background:    loading ? '#2a2624' : '#d60019',
                border:        'none',
                color:         loading ? '#5c5852' : '#0a0908',
                fontFamily:    '"JetBrains Mono", monospace',
                fontSize:       10,
                fontWeight:     700,
                letterSpacing:  2,
                padding:        '11px',
                cursor:         loading ? 'not-allowed' : 'pointer',
                transition:     'all .15s',
                textTransform: 'uppercase',
              }}
            >
              {loading ? 'EXPORTING...' : '↑ PUSH TO GITHUB'}
            </button>
          )}
        </div>
      </motion.div>
    </motion.div>
  );
}
