import { describe, it, expect } from 'vitest';
import { createServer, type Server } from 'node:http';
import type { AddressInfo } from 'node:net';
import { createGatewayHandler, GENERATE_MAX_BYTES, type GatewayConfig, type ProxyDeps } from '../server/gateway-proxy';

/**
 * Security + contract tests for the Vercel gateway proxy. The handler is
 * mounted on a real node:http server with an injected mock fetch that stands
 * in for the Konkred Gateway, so streaming, headers, status codes, abort
 * behaviour and rate limiting are all exercised over real TCP — without any
 * live provider, gateway or credential.
 */

const CONFIG: GatewayConfig = {
  gatewayUrl: 'https://gateway.konkred.test',
  gatewayApiKey: 'sk-gw-test-0123456789abcdef',
  fullkonkKey: 'brain-test-0123456789abcdef',
};

interface FetchCall {
  url: string;
  init: RequestInit & { headers: Record<string, string> };
}

interface Harness {
  baseUrl: string;
  calls: FetchCall[];
  logs: string[];
  close: () => Promise<void>;
}

async function mount(upstream: typeof fetch, deps: Partial<ProxyDeps> = {}): Promise<Harness> {
  const calls: FetchCall[] = [];
  const logs: string[] = [];
  const wrapped: typeof fetch = async (url: unknown, init?: RequestInit) => {
    calls.push({ url: String(url), init: init as FetchCall['init'] });
    return upstream(url as string, init);
  };
  const handler = createGatewayHandler({
    config: deps.config || CONFIG,
    fetchImpl: wrapped,
    log: deps.log || ((event) => logs.push(event)),
    cache: deps.cache || new Map(),
    limits: deps.limits,
    timeouts: deps.timeouts || { jsonMs: 5_000, connectMs: 1_000, idleMs: 1_000, overallMs: 5_000 },
    fallback: deps.fallback,
  });
  const server: Server = createServer((req, res) => {
    void handler(req, res);
  });
  await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve));
  const port = (server.address() as AddressInfo).port;
  return {
    baseUrl: `http://127.0.0.1:${port}`,
    calls,
    logs,
    close: () => new Promise((resolve) => server.close(() => resolve())),
  };
}

const jsonResponse = (status: number, payload: unknown, headers: Record<string, string> = {}): Response =>
  new Response(JSON.stringify(payload), {
    status,
    headers: { 'content-type': 'application/json', ...headers },
  });

const sseResponse = (frames: string[], opts: { frameDelayMs?: number; extraHeaders?: Record<string, string>; status?: number } = {}): Response => {
  const encoder = new TextEncoder();
  const stream = new ReadableStream({
    async start(controller) {
      for (let i = 0; i < frames.length; i += 1) {
        if (opts.frameDelayMs && i > 0) await new Promise((r) => setTimeout(r, opts.frameDelayMs));
        controller.enqueue(encoder.encode(frames[i]));
      }
      controller.close();
    },
  });
  return new Response(stream, {
    status: opts.status ?? 200,
    headers: { 'content-type': 'text/event-stream; charset=utf-8', ...(opts.extraHeaders || {}) },
  });
};

async function post(baseUrl: string, path: string, body: unknown, headers: Record<string, string> = {}): Promise<Response> {
  return fetch(`${baseUrl}${path}`, {
    method: 'POST',
    headers: { 'content-type': 'application/json', ...headers },
    body: typeof body === 'string' ? body : JSON.stringify(body),
  });
}

const validGenerateBody = () => ({ prompt: 'Build a todo app', mode: 'fullstack', provider: 'groq', model: 'llama', temperature: 0.4, maxTokens: 4096 });
const validAiBody = () => ({ taskType: 'general', messages: [{ role: 'user', content: 'Hello' }], maxTokens: 128, temperature: 0.3 });
const validExportBody = () => ({
  owner: 'octocat',
  repo: 'hello-world',
  branch: 'fullkonk-output',
  message: 'Generated by fullKONK',
  files: [{ path: 'src/index.ts', content: 'console.log(1)', language: 'typescript' }],
});

describe('gateway proxy — provider discovery', () => {
  it('proxies GET /api/fullkonk/providers and attaches x-brain-key server-side', async () => {
    const h = await mount(async () => jsonResponse(200, { providers: [{ id: 'groq', hasKey: true }] }));
    try {
      const res = await fetch(`${h.baseUrl}/api/fullkonk/providers`);
      expect(res.status).toBe(200);
      expect(res.headers.get('content-type')).toContain('application/json');
      const body = await res.json();
      expect(body.providers).toHaveLength(1);
      expect(h.calls).toHaveLength(1);
      expect(h.calls[0].url).toBe(`${CONFIG.gatewayUrl}/api/fullkonk/providers`);
      expect(h.calls[0].init.method).toBe('GET');
      expect(h.calls[0].init.headers['x-brain-key']).toBe(CONFIG.fullkonkKey);
    } finally { await h.close(); }
  });

  it('ignores a browser-spoofed x-brain-key', async () => {
    const h = await mount(async () => jsonResponse(200, { providers: [] }));
    try {
      const res = await fetch(`${h.baseUrl}/api/fullkonk/providers`, { headers: { 'x-brain-key': 'spoofed-brain' } });
      expect(res.status).toBe(200);
      expect(h.calls[0].init.headers['x-brain-key']).toBe(CONFIG.fullkonkKey);
      expect(h.calls[0].init.headers['x-brain-key']).not.toBe('spoofed-brain');
    } finally { await h.close(); }
  });

  it('caches a successful provider response briefly (one upstream call for two browser calls)', async () => {
    const cache = new Map();
    const h = await mount(async () => jsonResponse(200, { providers: [] }), { cache });
    try {
      await fetch(`${h.baseUrl}/api/fullkonk/providers`);
      await fetch(`${h.baseUrl}/api/fullkonk/providers`);
      expect(h.calls).toHaveLength(1);
    } finally { await h.close(); }
  });
});

describe('gateway proxy — standard inference /api/ai', () => {
  it('forwards the gateway contract with x-api-key and preserves the {ok,data} envelope', async () => {
    const h = await mount(async () => jsonResponse(200, { ok: true, data: { content: 'hi', provider: 'gemini' } }));
    try {
      const res = await post(h.baseUrl, '/api/ai', validAiBody());
      expect(res.status).toBe(200);
      const body = await res.json();
      expect(body.ok).toBe(true);
      expect(body.data.content).toBe('hi');
      expect(h.calls[0].url).toBe(`${CONFIG.gatewayUrl}/api/ai`);
      expect(h.calls[0].init.headers['x-api-key']).toBe(CONFIG.gatewayApiKey);
      expect(h.calls[0].init.headers['x-brain-key']).toBeUndefined();
      const forwarded = JSON.parse(h.calls[0].init.body as string);
      expect(forwarded).toMatchObject({ taskType: 'general', privacy: 'private', skipCache: false });
    } finally { await h.close(); }
  });

  it('strips a spoofed x-api-key from the browser', async () => {
    const h = await mount(async () => jsonResponse(200, { ok: true, data: { content: 'hi' } }));
    try {
      const res = await post(h.baseUrl, '/api/ai', validAiBody(), { 'x-api-key': 'spoofed-api' });
      expect(res.status).toBe(200);
      expect(h.calls[0].init.headers['x-api-key']).toBe(CONFIG.gatewayApiKey);
      expect(h.calls[0].init.headers['x-api-key']).not.toBe('spoofed-api');
    } finally { await h.close(); }
  });

  it('rejects malformed payloads with 400 and never reaches the gateway', async () => {
    const h = await mount(async () => jsonResponse(200, {}));
    try {
      const badMessages = await post(h.baseUrl, '/api/ai', { messages: [] });
      expect(badMessages.status).toBe(400);
      const badType = await post(h.baseUrl, '/api/ai', { messages: [{ role: 'nope', content: 'x' }] });
      expect(badType.status).toBe(400);
      const notJson = await post(h.baseUrl, '/api/ai', 'not-json');
      expect(notJson.status).toBe(400);
      expect(h.calls).toHaveLength(0);
      const bodies = await Promise.all([badMessages.json(), badType.json(), notJson.json()]);
      for (const b of bodies) expect(b.error).toBeTruthy();
    } finally { await h.close(); }
  });
});

describe('gateway proxy — SSE generation', () => {
  const frames = [
    'data: {"type":"stage","stage":"architect"}\n\n',
    'data: {"type":"provider","provider":"groq","model":"llama"}\n\n',
    'data: {"type":"delta","content":"export const x"}\n\n',
    'data: {"type":"file","file":{"path":"a.ts","content":"x","language":"typescript"}}\n\n',
    'data: {"type":"failover","from":"groq","to":"cerebras"}\n\n',
    'data: {"type":"metrics","data":{"tokensPerSecond":12,"totalTokens":50,"provider":"cerebras"}}\n\n',
    'data: {"type":"reset","characters":4}\n\n',
    'data: {"type":"done"}\n\n',
  ];

  it('streams SSE incrementally with the required no-buffer headers', async () => {
    const h = await mount(async () => sseResponse(frames, { frameDelayMs: 120 }));
    try {
      const res = await post(h.baseUrl, '/api/fullkonk/generate', validGenerateBody());
      expect(res.status).toBe(200);
      expect(res.headers.get('content-type')).toContain('text/event-stream');
      expect(res.headers.get('cache-control')).toContain('no-cache');
      expect(res.headers.get('cache-control')).toContain('no-transform');
      expect(res.headers.get('x-accel-buffering')).toBe('no');
      const reader = res.body!.getReader();
      const decoder = new TextDecoder();
      let received = '';
      const t0 = Date.now();
      let firstFrameAt = 0;
      for (;;) {
        const { done, value } = await reader.read();
        if (done) break;
        const text = decoder.decode(value, { stream: true });
        if (firstFrameAt === 0 && text.includes('stage')) firstFrameAt = Date.now() - t0;
        received += text;
      }
      const endedAt = Date.now() - t0;
      expect(firstFrameAt).toBeGreaterThanOrEqual(0);
      expect(firstFrameAt).toBeLessThan(400); // first frame flushes with/just after headers
      expect(endedAt).toBeGreaterThan(700);   // frames kept arriving over ~840ms of upstream time
      expect(endedAt - firstFrameAt).toBeGreaterThan(600); // NOT buffered until upstream closed
      expect(received).toContain('"type":"stage"');
      expect(received).toContain('"type":"done"');
      expect(h.calls[0].init.headers['x-brain-key']).toBe(CONFIG.fullkonkKey);
    } finally { await h.close(); }
  });

  it('passes BYOK x-provider-key only on the generate route', async () => {
    const h = await mount(async () => sseResponse(['data: {"type":"done"}\n\n']));
    try {
      await post(h.baseUrl, '/api/fullkonk/generate', validGenerateBody(), { 'x-provider-key': 'gsk_user_byok' });
      expect(h.calls[0].init.headers['x-provider-key']).toBe('gsk_user_byok');
    } finally { await h.close(); }

    const h2 = await mount(async () => jsonResponse(200, { providers: [] }));
    try {
      await fetch(`${h2.baseUrl}/api/fullkonk/providers`, { headers: { 'x-provider-key': 'gsk_user_byok' } });
      expect(h2.calls[0].init.headers['x-provider-key']).toBeUndefined();
    } finally { await h2.close(); }
  });

  it('aborts the upstream fetch when the browser disconnects', async () => {
    let upstreamAborted = () => {};
    const aborted = new Promise<void>((resolve) => { upstreamAborted = resolve; });
    const h = await mount(async (_url, init) => {
      init?.signal?.addEventListener('abort', () => upstreamAborted());
      const encoder = new TextEncoder();
      const stream = new ReadableStream({
        start(controller) {
          controller.enqueue(encoder.encode('data: {"type":"stage","stage":"architect"}\n\n'));
          // deliberately left open until the proxy aborts upstream
        },
      });
      return new Response(stream, { headers: { 'content-type': 'text/event-stream' } });
    });
    try {
      const controller = new AbortController();
      const real = await fetch(`${h.baseUrl}/api/fullkonk/generate`, {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify(validGenerateBody()),
        signal: controller.signal,
      });
      const reader = real.body!.getReader();
      await reader.read();
      controller.abort();
      await expect(aborted.then(() => true)).resolves.toBe(true);
    } finally { await h.close(); }
  });

  it('returns 504 when the gateway never connects (connect timeout)', async () => {
    const h = await mount(
      // Simulate undici: a connection that hangs until the abort signal fires.
      (_url, init) => new Promise<Response>((_resolve, reject) => {
        init?.signal?.addEventListener('abort', () => {
          const error = new Error('The operation was aborted');
          error.name = 'AbortError';
          reject(error);
        });
      }),
      { timeouts: { jsonMs: 5_000, connectMs: 150, idleMs: 1_000, overallMs: 5_000 } },
    );
    try {
      const res = await post(h.baseUrl, '/api/fullkonk/generate', validGenerateBody());
      expect(res.status).toBe(504);
      const body = await res.json();
      expect(body.error).toMatch(/timed out/i);
      expect(body.error).not.toContain(CONFIG.fullkonkKey);
    } finally { await h.close(); }
  });

  it('returns 502 (no internals) when the gateway is unreachable', async () => {
    const h = await mount(async () => { throw new TypeError('fetch failed: dial tcp 10.0.0.1:443'); });
    try {
      const res = await post(h.baseUrl, '/api/fullkonk/generate', validGenerateBody());
      expect(res.status).toBe(502);
      const body = await res.json();
      expect(body.retryable).toBe(true);
      expect(body.error).toMatch(/unreachable/i);
      expect(body.error).not.toMatch(/10\.0\.0\.1/);
    } finally { await h.close(); }
  });

  it('rejects invalid/over-sized generation bodies', async () => {
    const h = await mount(async () => sseResponse([]));
    try {
      const noPrompt = await post(h.baseUrl, '/api/fullkonk/generate', { mode: 'fullstack' });
      expect(noPrompt.status).toBe(400);
      const badTemperature = await post(h.baseUrl, '/api/fullkonk/generate', { prompt: 'x', temperature: 9 });
      expect(badTemperature.status).toBe(400);
      const notJson = await post(h.baseUrl, '/api/fullkonk/generate', '{broken');
      expect(notJson.status).toBe(400);
      expect(h.calls).toHaveLength(0);
    } finally { await h.close(); }

    const h2 = await mount(async () => sseResponse([]));
    try {
      const oversized = await post(h2.baseUrl, '/api/fullkonk/generate', { prompt: 'x'.repeat(GENERATE_MAX_BYTES + 10) });
      expect(oversized.status).toBe(413);
      const body = await oversized.json();
      expect(body.error).toMatch(/larger than the/);
      expect(h2.calls).toHaveLength(0);
    } finally { await h2.close(); }
  });
});

describe('gateway proxy — upstream status preservation', () => {
  it.each([401, 403, 413, 503])('preserves upstream %s', async (status) => {
    const h = await mount(async () => jsonResponse(status, { ok: false, error: `upstream ${status}` }));
    try {
      const res = await post(h.baseUrl, '/api/ai', validAiBody());
      expect(res.status).toBe(status);
      const body = await res.json();
      expect(body.error).toContain(String(status));
    } finally { await h.close(); }
  });

  it('preserves 429 and Retry-After for JSON routes', async () => {
    const h = await mount(async () => jsonResponse(429, { ok: false, error: 'slow down' }, { 'retry-after': '17' }));
    try {
      const res = await post(h.baseUrl, '/api/ai', validAiBody());
      expect(res.status).toBe(429);
      expect(res.headers.get('retry-after')).toBe('17');
    } finally { await h.close(); }
  });

  it('preserves 429 and Retry-After on the SSE route', async () => {
    const h = await mount(async () => sseResponse([], { status: 429, extraHeaders: { 'retry-after': '5', 'content-type': 'application/json' } }));
    try {
      const res = await post(h.baseUrl, '/api/fullkonk/generate', validGenerateBody());
      expect(res.status).toBe(429);
      expect(res.headers.get('retry-after')).toBe('5');
      expect(res.headers.get('content-type')).toContain('application/json');
    } finally { await h.close(); }
  });
});

describe('gateway proxy — GitHub export', () => {
  it('strips any browser-supplied token and forwards with x-brain-key', async () => {
    const h = await mount(async () => jsonResponse(200, { ok: true, data: { success: true, filesUploaded: 1, errors: [] } }));
    try {
      const body = { ...validExportBody(), token: 'ghp_should_never_reach_gateway_0000000000' };
      const res = await post(h.baseUrl, '/api/fullkonk/github/export', body);
      expect(res.status).toBe(200);
      const forwarded = JSON.parse(h.calls[0].init.body as string);
      expect(forwarded.token).toBeUndefined();
      expect(JSON.stringify(forwarded)).not.toContain('ghp_should_never_reach');
      expect(h.calls[0].init.headers['x-brain-key']).toBe(CONFIG.fullkonkKey);
      expect(h.calls[0].url).toBe(`${CONFIG.gatewayUrl}/api/fullkonk/github/export`);
    } finally { await h.close(); }
  });

  it('validates owner, repo, branch and file paths before proxying', async () => {
    const h = await mount(async () => jsonResponse(200, {}));
    try {
      const badOwner = await post(h.baseUrl, '/api/fullkonk/github/export', { ...validExportBody(), owner: 'bad/name' });
      expect(badOwner.status).toBe(400);
      const traversal = await post(h.baseUrl, '/api/fullkonk/github/export', { ...validExportBody(), files: [{ path: '../etc/passwd', content: 'x' }] });
      expect(traversal.status).toBe(400);
      const noFiles = await post(h.baseUrl, '/api/fullkonk/github/export', { ...validExportBody(), files: [] });
      expect(noFiles.status).toBe(400);
      const badBranch = await post(h.baseUrl, '/api/fullkonk/github/export', { ...validExportBody(), branch: 'refs/heads/x' });
      expect(badBranch.status).toBe(400);
      expect(h.calls).toHaveLength(0);
    } finally { await h.close(); }
  });
});

describe('gateway proxy — configuration, SSRF, methods and fallback', () => {
  it('returns a safe 503 when gateway URL / keys are missing', async () => {
    const h = await mount(async () => jsonResponse(200, {}), { config: { gatewayUrl: '', gatewayApiKey: '', fullkonkKey: '' } });
    try {
      const providers = await fetch(`${h.baseUrl}/api/fullkonk/providers`);
      expect(providers.status).toBe(503);
      expect((await providers.json()).code).toBe('GATEWAY_NOT_CONFIGURED');
      const ai = await post(h.baseUrl, '/api/ai', validAiBody());
      expect(ai.status).toBe(503);
      const gen = await post(h.baseUrl, '/api/fullkonk/generate', validGenerateBody());
      expect(gen.status).toBe(503);
      expect(h.calls).toHaveLength(0);
    } finally { await h.close(); }
  });

  it('returns 503 from /api/ai when only the gateway API key is missing', async () => {
    const h = await mount(async () => jsonResponse(200, {}), { config: { ...CONFIG, gatewayApiKey: '' } });
    try {
      const ai = await post(h.baseUrl, '/api/ai', validAiBody());
      expect(ai.status).toBe(503);
      // fullkonk brain-key routes still work because FULLKONK_KEY is set
      const providers = await fetch(`${h.baseUrl}/api/fullkonk/providers`);
      expect(providers.status).toBe(200);
    } finally { await h.close(); }
  });

  it('never accepts an upstream URL from the browser (SSRF)', async () => {
    const h = await mount(async () => jsonResponse(200, { ok: true, data: { content: 'x' } }));
    try {
      const body = { ...validAiBody(), gatewayUrl: 'http://169.254.169.254/latest/meta-data', url: 'http://evil.example', brainUrl: 'http://evil' };
      await post(h.baseUrl, '/api/ai', body, { 'x-gateway-url': 'http://evil.example' });
      expect(h.calls).toHaveLength(1);
      expect(h.calls[0].url).toBe(`${CONFIG.gatewayUrl}/api/ai`);
      const forwarded = JSON.parse(h.calls[0].init.body as string);
      expect(forwarded.gatewayUrl).toBeUndefined();
      expect(forwarded.url).toBeUndefined();
      expect(forwarded.brainUrl).toBeUndefined();
    } finally { await h.close(); }
  });

  it('rejects wrong HTTP methods with 405 and an Allow header', async () => {
    const h = await mount(async () => jsonResponse(200, {}));
    try {
      const del = await fetch(`${h.baseUrl}/api/ai`, { method: 'DELETE' });
      expect(del.status).toBe(405);
      expect(del.headers.get('allow')).toBe('POST');
      const put = await fetch(`${h.baseUrl}/api/fullkonk/providers`, { method: 'PUT' });
      expect(put.status).toBe(405);
      expect(put.headers.get('allow')).toBe('GET');
    } finally { await h.close(); }
  });

  it('denies cross-origin browser POSTs (CSRF defense)', async () => {
    const h = await mount(async () => jsonResponse(200, {}));
    try {
      const res = await post(h.baseUrl, '/api/ai', validAiBody(), { origin: 'https://evil.example' });
      expect(res.status).toBe(403);
      const sameOrigin = await post(h.baseUrl, '/api/ai', validAiBody(), { origin: h.baseUrl });
      expect(sameOrigin.status).toBe(200);
    } finally { await h.close(); }
  });

  it('falls through non-contracted routes to the legacy app', async () => {
    const fallen: string[] = [];
    const h = await mount(async () => jsonResponse(200, {}), {
      fallback: (req, res) => {
        fallen.push(req.url || '');
        res.statusCode = 200;
        res.setHeader('content-type', 'application/json');
        res.end(JSON.stringify({ legacy: true }));
      },
    });
    try {
      const sessions = await fetch(`${h.baseUrl}/api/fullkonk/sessions/abc?count=5`);
      expect(sessions.status).toBe(200);
      expect((await sessions.json()).legacy).toBe(true);
      // /api/health is NOT delegated any more: it is owned by the proxy so it
      // stays answerable even when the legacy bundle cannot be loaded.
      const health = await fetch(`${h.baseUrl}/api/health`);
      expect((await health.json()).legacy).toBeUndefined();
      const usage = await post(h.baseUrl, '/api/fullkonk/usage', { userId: 'abc' });
      expect(usage.status).toBe(200);
      const optimize = await post(h.baseUrl, '/api/fullkonk/optimize-prompt', { prompt: 'make it better' });
      expect(optimize.status).toBe(200);
      expect(fallen).toContain('/api/fullkonk/sessions/abc?count=5');
      expect(fallen.some((u) => u.startsWith('/api/fullkonk/optimize-prompt'))).toBe(true);
      expect(h.calls).toHaveLength(0);
    } finally { await h.close(); }
  });

  it('rate-limits abusive clients with 429 + Retry-After', async () => {
    const h = await mount(async () => jsonResponse(200, { ok: true, data: { content: 'x' } }), { limits: { ai: 2 } });
    try {
      const codes: number[] = [];
      let retryAfter: string | null = '';
      for (let i = 0; i < 4; i += 1) {
        const r = await post(h.baseUrl, '/api/ai', validAiBody());
        codes.push(r.status);
        retryAfter = r.headers.get('retry-after');
      }
      expect(codes.slice(0, 2)).toEqual([200, 200]);
      expect(codes[2]).toBe(429);
      expect(Number(retryAfter)).toBeGreaterThan(0);
    } finally { await h.close(); }
  });
});

describe('gateway proxy — secret screening and redacted logs', () => {
  it('never relays a gateway credential leaked inside an upstream JSON body', async () => {
    const h = await mount(async () => jsonResponse(500, { ok: false, error: `internal ${CONFIG.fullkonkKey}` }));
    try {
      const res = await fetch(`${h.baseUrl}/api/fullkonk/providers`);
      expect(res.status).toBe(502);
      const text = await res.text();
      expect(text).not.toContain(CONFIG.fullkonkKey);
    } finally { await h.close(); }
  });

  it('aborts an upstream SSE stream that starts emitting a secret', async () => {
    const frames = [
      'data: {"type":"delta","content":"safe part"}\n\n',
      `data: {"type":"delta","content":"${CONFIG.fullkonkKey}"}\n\n`,
      'data: {"type":"done"}\n\n',
    ];
    const h = await mount(async () => sseResponse(frames));
    try {
      const res = await post(h.baseUrl, '/api/fullkonk/generate', validGenerateBody());
      const text = await res.text();
      expect(text).not.toContain(CONFIG.fullkonkKey);
    } finally { await h.close(); }
  });

  it('server logs never contain credentials or bodies', async () => {
    const h = await mount(async () => jsonResponse(500, { error: CONFIG.gatewayApiKey }));
    try {
      await post(h.baseUrl, '/api/ai', validAiBody());
      const allLogs = h.logs.join('\n');
      expect(allLogs).not.toContain(CONFIG.gatewayApiKey);
      expect(allLogs).not.toContain(CONFIG.fullkonkKey);
      expect(allLogs.toLowerCase()).not.toContain('authorization');
    } finally { await h.close(); }
  });
});

/**
 * Regression suite for the production incident in which every /api/* route
 * returned `500 FUNCTION_INVOCATION_FAILED`.
 *
 * The health contract must hold under the exact conditions that caused the
 * outage: no configuration at all, and an unreachable gateway. In both cases
 * the function must answer with controlled JSON.
 */
describe('health contract (incident regression)', () => {
  const UNCONFIGURED: GatewayConfig = { gatewayUrl: '', gatewayApiKey: '', fullkonkKey: '' };

  it('GET /api/health is 200 even with no configuration and no legacy app', async () => {
    const h = await mount(async () => jsonResponse(200, {}), { config: UNCONFIGURED });
    try {
      const res = await fetch(`${h.baseUrl}/api/health`);
      expect(res.status).toBe(200);
      const body = await res.json();
      expect(body.status).toBe('ok');
      expect(body.service).toBe('konkred-website');
      // Booleans only — never the values themselves.
      expect(body.configured).toEqual({ gatewayUrl: false, gatewayApiKey: false, fullkonkKey: false });
      // The gateway must not even be contacted for a liveness probe.
      expect(h.calls).toHaveLength(0);
    } finally { await h.close(); }
  });

  it('GET /api/health never leaks secret values, only booleans', async () => {
    const h = await mount(async () => jsonResponse(200, {}));
    try {
      const raw = await (await fetch(`${h.baseUrl}/api/health`)).text();
      expect(raw).not.toContain(CONFIG.gatewayApiKey);
      expect(raw).not.toContain(CONFIG.fullkonkKey);
      expect(raw).not.toContain(CONFIG.gatewayUrl);
      expect(JSON.parse(raw).configured.fullkonkKey).toBe(true);
    } finally { await h.close(); }
  });

  it('GET /api/ready reports 503 GATEWAY_NOT_CONFIGURED instead of crashing', async () => {
    const h = await mount(async () => jsonResponse(200, {}), { config: UNCONFIGURED });
    try {
      const res = await fetch(`${h.baseUrl}/api/ready`);
      expect(res.status).toBe(503);
      const body = await res.json();
      expect(body.code).toBe('GATEWAY_NOT_CONFIGURED');
      expect(body.status).toBe('degraded');
    } finally { await h.close(); }
  });

  it('GET /api/ready reports 200 when the gateway answers its health probe', async () => {
    const h = await mount(async () => jsonResponse(200, { status: 'ok' }));
    try {
      const res = await fetch(`${h.baseUrl}/api/ready`);
      expect(res.status).toBe(200);
      const body = await res.json();
      expect(body.status).toBe('ok');
      expect(body.gateway.reachable).toBe(true);
      expect(h.calls[0].url).toBe(`${CONFIG.gatewayUrl}/api/health`);
    } finally { await h.close(); }
  });

  it('GET /api/ready degrades to 503 GATEWAY_UNREACHABLE on a network failure', async () => {
    const h = await mount(async () => { throw new Error('ECONNREFUSED'); });
    try {
      const res = await fetch(`${h.baseUrl}/api/ready`);
      expect(res.status).toBe(503);
      const body = await res.json();
      expect(body.code).toBe('GATEWAY_UNREACHABLE');
      expect(body.gateway.reachable).toBe(false);
    } finally { await h.close(); }
  });

  it('GET /api/ready degrades to 503 GATEWAY_UNHEALTHY when the gateway errors', async () => {
    const h = await mount(async () => jsonResponse(502, { error: 'bad' }));
    try {
      const res = await fetch(`${h.baseUrl}/api/ready`);
      expect(res.status).toBe(503);
      expect((await res.json()).code).toBe('GATEWAY_UNHEALTHY');
    } finally { await h.close(); }
  });

  it('a gateway outage degrades /api/ready but never /api/health', async () => {
    const h = await mount(async () => { throw new Error('ECONNREFUSED'); });
    try {
      expect((await fetch(`${h.baseUrl}/api/ready`)).status).toBe(503);
      // Liveness must stay green: the Vercel function itself is fine.
      expect((await fetch(`${h.baseUrl}/api/health`)).status).toBe(200);
    } finally { await h.close(); }
  });

  it('health routes do not require the legacy fallback to be usable', async () => {
    // Simulates the deployment where importing the bundled Express app throws
    // (missing firebase-admin / pg configuration) — the original crash source.
    const h = await mount(async () => jsonResponse(200, {}), {
      config: UNCONFIGURED,
      fallback: () => { throw new Error('legacy app is unavailable'); },
    });
    try {
      expect((await fetch(`${h.baseUrl}/api/health`)).status).toBe(200);
      expect((await fetch(`${h.baseUrl}/api/ready`)).status).toBe(503);
    } finally { await h.close(); }
  });
});
