/**
 * POST /api/fullkonk/github/export — secure GitHub export proxy.
 *
 * Browser → this Vercel route → ${KONKRED_GATEWAY_URL}/api/fullkonk/github/export
 *
 * Credential model (documented in docs/fullkonk/GATEWAY_INTEGRATION.md):
 *   • If FULLKONK_GITHUB_EXPORT_TOKEN is set on the deployment, that
 *     server-owned token is used and ANY token in the request body is ignored.
 *   • Otherwise the signed-in user's own fine-grained token is accepted (BYOK,
 *     exactly like the existing UI). It is forwarded straight to the gateway,
 *     never stored, never logged and never echoed back.
 *
 * The gateway shared secret (x-brain-key) always comes from server env — the
 * browser cannot supply credentials for the upstream hop.
 */
import type { IncomingMessage, ServerResponse } from 'node:http';
import { GATEWAY_PATHS, isGatewayConfigured, readGatewayConfig, resolveUpstreamUrl } from '../config';
import { authenticateRequest } from '../auth';
import {
  fail,
  isHttpFailure,
  isOriginAllowed,
  log,
  methodNotAllowed,
  rateLimiter,
  readJsonBody,
  redactSecrets,
  requestId,
  sendJson,
} from '../http';
import { callGatewayJson, parseGatewayError } from '../upstream';

const MAX_FILES = 200;
const MAX_FILE_BYTES = 400 * 1024;
const MAX_TOTAL_BYTES = 2 * 1024 * 1024;
const MAX_PATH_CHARS = 400;
// GitHub allows letters, digits, '.', '_' and '-' anywhere in owner/repo names
// (the 'konkred_xyz-' repository is a live example). Path separators stay banned
// so owner/repo can never inject an extra API path segment.
const OWNER_REPO = /^[A-Za-z0-9._-]{1,100}$/;
const BRANCH_RE = /^[A-Za-z0-9](?:[A-Za-z0-9._/-]{0,118}[A-Za-z0-9])?$/;
const TOKEN_RE = /^(?:gh[pousr]_[A-Za-z0-9_]{20,255}|github_pat_[A-Za-z0-9_]{20,255})$/;

export interface NormalizedExportFile {
  path: string;
  content: string;
}

export interface NormalizedExportRequest {
  token: string;
  owner: string;
  repo: string;
  branch: string;
  message: string;
  files: NormalizedExportFile[];
}

const safeFilePath = (path: string): boolean => {
  if (!path || path.length > MAX_PATH_CHARS) return false;
  if (path.startsWith('/') || path.includes('\\') || path.includes('\0')) return false;
  if (path.includes('..')) return false;
  if (path.toLowerCase().startsWith('.git/')) return false;
  return true;
};

export const normalizeExportRequest = (
  raw: unknown,
  serverToken = '',
): NormalizedExportRequest => {
  const body = raw && typeof raw === 'object' && !Array.isArray(raw) ? (raw as Record<string, unknown>) : {};

  const owner = typeof body.owner === 'string' ? body.owner.trim() : '';
  const repo = typeof body.repo === 'string' ? body.repo.trim() : '';
  if (!OWNER_REPO.test(owner)) throw fail(400, 'BAD_REQUEST', 'A valid GitHub owner or organisation is required.');
  if (!OWNER_REPO.test(repo)) throw fail(400, 'BAD_REQUEST', 'A valid GitHub repository name is required.');

  const branch = (typeof body.branch === 'string' && body.branch.trim()) || 'fullkonk-output';
  if (!BRANCH_RE.test(branch) || branch.includes('..') || branch.includes('//') || branch.endsWith('/')) {
    throw fail(400, 'BAD_REQUEST', 'A valid branch name is required (letters, digits, . _ - /).');
  }

  const message = typeof body.message === 'string' && body.message.trim()
    ? body.message.trim().slice(0, 200)
    : 'Generated by fullKONK_> · konkred.xyz';

  const clientToken = typeof body.token === 'string' ? body.token.trim() : '';
  const token = serverToken || clientToken;
  if (!token) {
    throw fail(400, 'BAD_REQUEST', 'A GitHub token is required for the export.');
  }
  if (!TOKEN_RE.test(token)) {
    throw fail(400, 'BAD_REQUEST', 'A valid GitHub token (ghp_… / github_pat_…) is required.');
  }

  const rawFiles = body.files;
  if (!Array.isArray(rawFiles) || rawFiles.length === 0) throw fail(400, 'BAD_REQUEST', 'At least one generated file is required.');
  if (rawFiles.length > MAX_FILES) throw fail(413, 'PAYLOAD_TOO_LARGE', `At most ${MAX_FILES} files can be exported per request.`);

  const files: NormalizedExportFile[] = [];
  let total = 0;
  for (const item of rawFiles) {
    const file = item && typeof item === 'object' ? (item as Record<string, unknown>) : {};
    const path = typeof file.path === 'string' ? file.path.trim().replace(/^\.\//, '') : '';
    if (!safeFilePath(path)) throw fail(400, 'BAD_REQUEST', 'Every file path must be relative and must not escape the repository.');
    const content = typeof file.content === 'string' ? file.content : '';
    const bytes = Buffer.byteLength(content, 'utf8');
    if (bytes > MAX_FILE_BYTES) throw fail(413, 'PAYLOAD_TOO_LARGE', `${path} exceeds the 400KB per-file limit.`);
    total += bytes;
    if (total > MAX_TOTAL_BYTES) throw fail(413, 'PAYLOAD_TOO_LARGE', 'The export payload is too large (2MB total).');
    files.push({ path, content });
  }

  return { token, owner, repo, branch, message, files };
};

export const handleGitHubExport = async (req: IncomingMessage, res: ServerResponse): Promise<void> => {
  const id = requestId();
  if (req.method !== 'POST') {
    methodNotAllowed(res, 'POST');
    return;
  }

  const config = readGatewayConfig();
  if (!isGatewayConfigured(config)) {
    sendJson(res, 503, { success: false, filesUploaded: 0, prUrl: null, errors: ['Export is not configured on this deployment.'], code: 'GATEWAY_NOT_CONFIGURED' });
    return;
  }
  if (!isOriginAllowed(req, config.allowedOrigins)) {
    log.warn('bff.export', `origin rejected id=${id}`);
    sendJson(res, 403, { success: false, filesUploaded: 0, prUrl: null, errors: ['This origin is not allowed to export.'], code: 'FORBIDDEN' });
    return;
  }

  const caller = await authenticateRequest(req, config);
  if (isHttpFailure(caller)) {
    sendJson(res, caller.status, { success: false, filesUploaded: 0, prUrl: null, errors: [caller.message], code: caller.code }, { 'cache-control': 'no-store' });
    return;
  }

  const limit = rateLimiter.check(`export:${caller.id}`, config.rateLimits.export);
  if (!limit.ok) {
    log.warn('bff.export', `rate limited id=${id}`);
    sendJson(
      res,
      429,
      { success: false, filesUploaded: 0, prUrl: null, errors: ['Too many exports. Try again shortly.'], code: 'RATE_LIMITED' },
      { 'cache-control': 'no-store', 'retry-after': String(limit.retryAfterSec) },
    );
    return;
  }

  let payload: NormalizedExportRequest;
  try {
    payload = normalizeExportRequest(await readJsonBody(req, config.maxBodyBytes), config.githubExportToken);
  } catch (error) {
    sendJson(
      res,
      isHttpFailure(error) ? error.status : 400,
      {
        success: false,
        filesUploaded: 0,
        prUrl: null,
        errors: [redactSecrets(error instanceof Error ? error.message : 'The export request is not valid.')],
        code: isHttpFailure(error) ? error.code : 'BAD_REQUEST',
      },
      { 'cache-control': 'no-store' },
    );
    return;
  }

  const started = Date.now();
  const result = await callGatewayJson({
    config,
    url: resolveUpstreamUrl(config, GATEWAY_PATHS.githubExport),
    method: 'POST',
    credential: { header: 'x-brain-key', value: config.fullkonkKey },
    body: payload,
    timeoutMs: Math.min(config.connectTimeoutMs * 3, 120_000),
    maxBytes: config.maxUpstreamErrorBytes,
  });

  if (!result.ok || !result.response) {
    const failure = result.failure ?? fail(502, 'GATEWAY_UNAVAILABLE', 'The Konkred Gateway is unreachable. Try again shortly.');
    log.warn('bff.export', `upstream unreachable id=${id} code=${failure.code} ms=${Date.now() - started}`);
    sendJson(
      res,
      failure.status,
      { success: false, filesUploaded: 0, prUrl: null, errors: [failure.message], code: failure.code },
      { 'cache-control': 'no-store' },
    );
    return;
  }

  const response = result.response;

  // Never surface the token or file contents: the gateway envelope is rebuilt
  // from its known fields only, and every error string is redacted.
  const projectEnvelope = (): string => {
    if (response.status >= 400) {
      const error = parseGatewayError(response.body, response.status);
      return JSON.stringify({ success: false, filesUploaded: 0, prUrl: null, errors: [error.message], code: error.code });
    }
    let parsed: Record<string, unknown>;
    try {
      parsed = JSON.parse(response.body.toString('utf8')) as Record<string, unknown>;
    } catch {
      return JSON.stringify({
        success: false,
        filesUploaded: 0,
        prUrl: null,
        errors: ['The gateway returned a malformed export response.'],
        code: 'UPSTREAM_ERROR',
      });
    }
    const errors = Array.isArray(parsed.errors) ? parsed.errors.slice(0, 20).map((item) => redactSecrets(String(item))) : [];
    return JSON.stringify({
      success: Boolean(parsed.success),
      filesUploaded: Number.isFinite(Number(parsed.filesUploaded)) ? Number(parsed.filesUploaded) : 0,
      prUrl: typeof parsed.prUrl === 'string' && parsed.prUrl ? parsed.prUrl : null,
      errors,
    });
  };
  const safeBody = projectEnvelope();

  res.writeHead(response.status, {
    'content-type': 'application/json; charset=utf-8',
    'content-length': String(Buffer.byteLength(safeBody)),
    'cache-control': 'no-store',
    ...(response.retryAfter ? { 'retry-after': response.retryAfter } : {}),
  });
  res.end(safeBody);
  log.info('bff.export', `export id=${id} status=${response.status} files=${payload.files.length} ms=${Date.now() - started}`);
};
